config/routes.rb
# Routes for the server side pages
Rails.application.routes.draw do
  # Routes for devise user authentication
  #
  # We let rails handle this, because devise provides us a nice interface
  #
  devise_for :users, controllers: { sessions: 'sessions' }

  # Home route.  Redirects to devise if no user is signed in, and angular if there
  # is an authenticated user.
  #
  root to: 'home#index'

  # Routes for API calls only.  These shouldn't respond to HTML requests
  #
  namespace :api do

  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/user.rb
# Class to interface with the 'users' database table
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# Controller parent class
#
# Contains the current_user definition
#
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Ensure we have a logged in user in all controllers
  check_authorization unless: :devise_controller?

  # Set up params for devise controllers
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Errors and redirects for unauthorized access
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message

    respond_to do |format|
      format.html do
        # Devise takes this and makes it the first page to load after the person logs in
        session[:user_return_to] = request.url if !signed_in? && request.get?
        redirect_to root_url
      end
      format.json do
        render json: flash, status: :unauthorized
        flash.delete( :error )
      end
      format.js do
        render 'shared/error'
        flash.delete( :error )
      end
    end
  end

  protected

  def configure_permitted_parameters
    # Set parameters for devise sign_up method
    devise_parameter_sanitizer.for( :sign_up ) << :username
    devise_parameter_sanitizer.for( :sign_up ) << :password_confirmation
    # Set parameters for devise sign_in method
    devise_parameter_sanitizer.for( :sign_in ) << :username
    devise_parameter_sanitizer.for( :sign_in ) << :password_confirmation
    # Set parameters for devise account update method
    devise_parameter_sanitizer.for( :account_update ) << :username
    devise_parameter_sanitizer.for( :account_update ) << :password_confirmation
  end

  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end
end

app/controllers/home_controller.rb
# Controller to handle the main route.
#
# Currently this will direct to the login page when no current_user exists,
# and to the angular page otherwise
#
class HomeController < ApplicationController
  skip_authorization_check

  layout 'angular'
  #
  # Method to show the login page
  #
  def index
    # Once someone signs in, hand things over to the angular page
    if current_user && user_signed_in?
      render 'index'
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
# View Helpers for the Home Controller
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/index.html.erb
<body ng-app="myApp">
  <div class="container">
    <div class="header">
      <ul class="nav nav-pills pull-right">
        <li class="active"><a ng-href="#">Home</a></li>
        <li><a ng-href="#/about">About</a></li>
        <li><a href='/users/sign_out' target='_self' data-method='delete'>Sign Out</a></li>
      </ul>
      <h3 class="text-muted"><%= t( 'app_name', name: RailsAngularDevise::Application.config.app_name ) %> - angular page</h3>
    </div>

    <div ng-view=""></div>

  </div>
</body>

app/views/home/login.html.erb
<div id='login_content' class='container'>
  <div class='row'>
    <div class='col-xs-12 text-center'>
      <h1>
        <%= t( 'welcome' ) %> <%= t( 'app_name', name: RailsAngularDevise::Application.config.app_name ) %>
      </h1>
    </div>
  </div>

  <%= form_for( resource, as: resource_name, url: session_path( resource_name ) ) do |f| %>
    <%= devise_error_messages! %>
    <div class='row form-group'>
      <div class='col-xs-6 col-sm-4 col-sm-offset-2 col-md-3 col-md-offset-3 col-lg-2 col-lg-offset-4 text-right'>
        <%= f.text_field :email, tabindex: 1, id: 'email_field', autofocus: true, placeholder: t( 'email_label' ), class: 'form-control' %>
      </div>
      <div class='col-xs-6 col-sm-4 col-md-3 col-lg-2'>
        <%= f.password_field :password, tabindex: 2, autocomplete: 'off', id: 'password_field', placeholder: t( 'password_label' ), class: 'form-control' %>
      </div>
    </div>
    <% if devise_mapping.rememberable? -%>
      <div class='row form-group'>
        <div class='col-xs-12 text-center'>
          <%= f.check_box :remember_me, tabindex: 3 %> <%= f.label :remember_me, t( 'remember_me' ) %>
        </div>
      </div>
    <% end %>
    <div class='row form-group'>
      <div class='col-xs-12 text-center'>
        <%= f.submit t( 'sign_in' ), id: 'log_in_button', class: 'btn btn-primary', tabindex: 4 %>
      </div>
    </div>
  <% end %>
  <%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
    <div class='row form-group'>
      <div class='col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4'>
        <hr/>
      </div>
    </div>
    <div class='row form-group'>
      <div class='col-xs-6 col-sm-4 col-sm-offset-2 col-md-3 col-md-offset-3 col-lg-2 col-lg-offset-4 text-center'>
        <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
          <%= link_to t( 'sign_up' ), new_registration_path( resource_name ), class: 'form-control btn-link' %>
        <% end -%>
      </div>
      <div class='col-xs-6 col-sm-4 col-md-3 col-lg-2 text-center'>
        <span class='forgot'><%= link_to t( 'forgot_password' ), new_password_path( resource_name ), class: 'form-control btn-link' %></span>
      </div>
    </div>
  <% end -%>
</div>

app/views/layouts/angular.html.erb
<!DOCTYPE html>
<html class='no-js'>
<head>
  <title><%= RailsAngularDevise::Application.config.app_name %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'ng-application' %>
  <%= csrf_meta_tags %>
  <!-- This meta tag makes the site scale correctly for mobile browsers -->
  <meta name='viewport' content='width=device-width; initial-scale=1.0; maximum-scale=1.0;'/>
</head>

  <%= yield %>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= RailsAngularDevise::Application.config.app_name %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!-- This meta tag makes the site scale correctly for mobile browsers -->
  <meta name='viewport' content='width=device-width; initial-scale=1.0; maximum-scale=1.0;'/>
</head>
<body>
  <div id='notification'>
    <% if flash[:notice] %>
      <div class='alert alert-success'>
        <%= link_to "×", "", class: "close" %>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class='alert'>
        <%= link_to "×", "", class: "close" %>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class='alert alert-error'>
        <%= link_to "×", "", class: "close" %>
        <%= flash[:error] %>
      </div>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/shared/error.js.erb
alert( '<%= flash[:error] %>' );